export { publicRoutes } from './public';
export { dashboardRoutes } from './dashboard';
export { componentsRoutes } from './components';
export { eventsRoutes } from './events';
export { usersRoutes } from './users';
export { formsRoutes } from './forms';
export { settingsRoutes } from './settings';
export { demoRoutes } from './demo';
export { systemRoutes } from './system';
