#!/bin/bash

# --- 環境變數設置腳本 ---
# 統一管理所有環境變數，避免重複維護

# 設置預設環境變數 (這些變數設定將會被 Docker Compose 讀取)
export NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-https://api.nx-playground.local}
export NEXT_PUBLIC_API_TIMEOUT=${NEXT_PUBLIC_API_TIMEOUT:-10000}
export NEXT_PUBLIC_LIFF_ID=${NEXT_PUBLIC_LIFF_ID:-2007835339-AmngJedQ}
export NEXT_PUBLIC_LINE_CLIENT_ID=${NEXT_PUBLIC_LINE_CLIENT_ID:-2007835339}
export NEXT_PUBLIC_LINE_REDIRECT_URI=${NEXT_PUBLIC_LINE_REDIRECT_URI:-https://frontend.oosa.life}
export LINE_CLIENT_SECRET=${LINE_CLIENT_SECRET:-your_line_client_secret_here}
export NEXT_PUBLIC_PRODUCTION_DOMAIN=${NEXT_PUBLIC_PRODUCTION_DOMAIN:-https://frontend.oosa.life}
export NEXT_PUBLIC_DEVELOPMENT_DOMAIN=${NEXT_PUBLIC_DEVELOPMENT_DOMAIN:-http://localhost:3000}
export NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:-NX Playground Events}
export NEXT_PUBLIC_APP_VERSION=${NEXT_PUBLIC_APP_VERSION:-1.0.0}
export NEXT_PUBLIC_ENABLE_DEVTOOLS=${NEXT_PUBLIC_ENABLE_DEVTOOLS:-true}
export NEXT_PUBLIC_ENABLE_MOCK_DATA=${NEXT_PUBLIC_ENABLE_MOCK_DATA:-true}
export VITE_APP_NAME=${VITE_APP_NAME:-NX Playground Console}
export VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}

# 新增這行：動態設定 Next.js 開發環境使用 HTTPS
export HTTPS=true

# 生成 .env 文件供 Next.js 和 Docker 使用
cat > .env << EOF
# Events 專案的環境變數
NEXT_PUBLIC_LIFF_ID=${NEXT_PUBLIC_LIFF_ID:-2007835339-AmngJedQ}
NEXT_PUBLIC_LINE_CLIENT_ID=${NEXT_PUBLIC_LINE_CLIENT_ID:-2007835339}
LINE_CLIENT_SECRET=${LINE_CLIENT_SECRET:-your_line_client_secret_here}
NEXT_PUBLIC_LINE_REDIRECT_URI=${NEXT_PUBLIC_LINE_REDIRECT_URI:-https://frontend.oosa.life}
NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-https://api.nx-playground.local}
NEXT_PUBLIC_API_TIMEOUT=${NEXT_PUBLIC_API_TIMEOUT:-10000}
NEXT_PUBLIC_PRODUCTION_DOMAIN=${NEXT_PUBLIC_PRODUCTION_DOMAIN:-https://frontend.oosa.life}
NEXT_PUBLIC_DEVELOPMENT_DOMAIN=${NEXT_PUBLIC_DEVELOPMENT_DOMAIN:-http://localhost:3000}
NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:-NX Playground Events}
NEXT_PUBLIC_APP_VERSION=${NEXT_PUBLIC_APP_VERSION:-1.0.0}
NEXT_PUBLIC_ENABLE_DEVTOOLS=${NEXT_PUBLIC_ENABLE_DEVTOOLS:-true}
NEXT_PUBLIC_ENABLE_MOCK_DATA=${NEXT_PUBLIC_ENABLE_MOCK_DATA:-true}

# Console 專案的環境變數
VITE_APP_NAME=${VITE_APP_NAME:-NX Playground Console}
VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
EOF
