name: Deploy Profile to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - 'apps/profile/**'
      - 'libs/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build profile app
        run: pnpm exec nx build @nx-playground/profile --configuration=production

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: nx-playground-profile
          directory: dist/apps/profile
          # Optional: Git integration
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
